/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 dinosaur.gltf 
Author: zixisun02 (https://sketchfab.com/zixisun51)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/dinosaur-3e12af7c5c354ea6b01bccfb529a9c02
Title: Dinosaur
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Dinosaur(props) {
  const { nodes, materials } = useGLTF('/models/dinosaur/dinosaur.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh scale={1.1} geometry={nodes.Dino_Dino_0.geometry} material={materials.Dino} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload("/models/dinosaur/dinosaur.gltf");
